 web:
    image: satyaprakashyadav/tomcatapp:tomcat
    ports:
    - "8088:8088"
    links:
    - db
    environment:
    - DBCONNECTIONIP=db
 db:
   image: mysql
   volumes:
   - /home/IMPETUS/satyaprakash.yadav/Docker/mysql/datadir:/var/lib/mysql
   environment:
   - MYSQL_ROOT_PASSWORD=root
